# Generated by Django 6.0.4 on 2026-04-08 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_id', models.CharField(max_length=50)),
                ('coupon_id', models.CharField(max_length=50, unique=True)),
                ('coupon_meal', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('S', 'Snacks'), ('D', 'Dinner')], max_length=1)),
                ('coupon_qr', models.TextField()),
                ('coupon_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='core.student')),
            ],
        ),
    ]
