# Generated by Django 6.0.4 on 2026-04-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='coupon_qr',
        ),
        migrations.AddField(
            model_name='coupon',
            name='qr_image',
            field=models.ImageField(blank=True, upload_to='coupon_qr/'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='qr_payload',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
