# Generated by Django 6.0.4 on 2026-04-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_coupon_coupon_qr_coupon_qr_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='qr_payload',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(fields=('student', 'hostel_id', 'coupon_meal', 'coupon_date'), name='unique_daily_coupon_per_student_meal_hostel'),
        ),
    ]
