# Generated by Django 6.0.4 on 2026-04-08 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_coupon_qr_payload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('hostel_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MessMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('meal', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('S', 'Snacks'), ('D', 'Dinner')], max_length=1)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='core.mess')),
            ],
        ),
        migrations.CreateModel(
            name='MessMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.messmenu')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='messmenu',
            constraint=models.UniqueConstraint(fields=('mess', 'day_of_week', 'meal'), name='unique_menu_per_mess_day_meal'),
        ),
    ]
