# Generated by Django 6.0.4 on 2026-04-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mess_messmenu_messmenuitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mess',
            name='mess_id',
        ),
    ]
