# Generated by Django 6.0.4 on 2026-04-08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_complaint_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='coupon_meal',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('S', 'Snacks'), ('D', 'Dinner')], default='L', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='mess',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='core.mess'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='raised_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='coupon_meal',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('S', 'Snacks'), ('D', 'Dinner')], default='L', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='raised_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
