# Generated by Django 6.0.4 on 2026-04-08

import django.db.models.deletion
from django.db import migrations, models


def forwards_populate_user_mess(apps, schema_editor):
    Mess = apps.get_model('core', 'Mess')
    Student = apps.get_model('core', 'Student')
    Staff = apps.get_model('core', 'Staff')

    for student in Student.objects.all().iterator():
        mess = Mess.objects.filter(hostel_id=student.hostel_id).order_by('id').first()
        if mess is None:
            mess = Mess.objects.create(
                name=f'Hostel {student.hostel_id} Mess',
                hostel_id=student.hostel_id,
            )
        student.mess_id = mess.id
        student.save(update_fields=['mess'])

    for staff in Staff.objects.all().iterator():
        mess = Mess.objects.filter(hostel_id=staff.hostel_id).order_by('id').first()
        if mess is None:
            mess = Mess.objects.create(
                name=f'Hostel {staff.hostel_id} Mess',
                hostel_id=staff.hostel_id,
            )
        staff.mess_id = mess.id
        staff.save(update_fields=['mess'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_feedback_complaint_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='mess',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='staff_members',
                to='core.mess',
            ),
        ),
        migrations.AddField(
            model_name='student',
            name='mess',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='students',
                to='core.mess',
            ),
        ),
        migrations.RunPython(forwards_populate_user_mess, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='staff',
            name='mess',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='staff_members',
                to='core.mess',
            ),
        ),
        migrations.AlterField(
            model_name='student',
            name='mess',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='students',
                to='core.mess',
            ),
        ),
        migrations.RemoveField(
            model_name='staff',
            name='hostel_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hostel_id',
        ),
    ]
