# Generated by Django 6.0.4 on 2026-04-09

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_mess_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='core.coupon')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_transfer_requests_sent', to='core.student')),
                ('requested_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_transfer_requests_received', to='core.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='coupontransferrequest',
            constraint=models.UniqueConstraint(condition=Q(status='pending'), fields=('coupon',), name='unique_pending_transfer_per_coupon'),
        ),
    ]