# Generated by Django 6.0.4 on 2026-04-09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_coupontransferrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='qr_payload',
            field=models.TextField(blank=True),
        ),
    ]