# Generated by Django 6.0.4 on 2026-04-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_coupon_valid_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
