# Generated by Django 6.0.4 on 2026-04-13 07:41

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_coupon_valid_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='photo',
            field=models.ImageField(storage=core.storage.PublicSupabaseStorage(), upload_to='complaints/'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='qr_image',
            field=models.ImageField(blank=True, storage=core.storage.PrivateQrSupabaseStorage(), upload_to='coupon_qr/'),
        ),
    ]
