# Generated by Django 6.0.4 on 2026-04-13 11:56

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_complaint_photo_alter_coupon_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='qr_image',
            field=models.ImageField(blank=True, storage=core.storage.PrivateQrSupabaseStorage(), upload_to=''),
        ),
    ]
