# Generated by Django 6.0.4 on 2026-04-18 10:06

import django.utils.timezone
from django.db import migrations, models
import django.db.models
import django.db.models.functions


def backfill_feedback_submitted_on(apps, schema_editor):
    Feedback = apps.get_model('core', 'Feedback')
    Feedback.objects.filter(submitted_on__isnull=True).update(
        submitted_on=django.db.models.functions.TruncDate('created_at')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_feedback_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='complaint',
            name='submitted_on',
            field=models.DateField(blank=True, db_index=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='submitted_on',
            field=models.DateField(blank=True, db_index=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.RunPython(backfill_feedback_submitted_on, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.UniqueConstraint(condition=django.db.models.Q(('submitted_on__isnull', False)), fields=('raised_by', 'coupon_meal', 'submitted_on'), name='unique_complaint_per_user_meal_day'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(condition=django.db.models.Q(('submitted_on__isnull', False)), fields=('raised_by', 'coupon_meal', 'submitted_on'), name='unique_feedback_per_user_meal_day'),
        ),
    ]
