# Generated by Django 6.0.4 on 2026-04-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_complaint_created_at_complaint_submitted_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
